MyWebApi/Controllers/DataBookController.cs
using Microsoft.AspNetCore.Mvc;
using MyWebApiView.Models;
using MyWebApiView.Interfaces;
using Microsoft.AspNetCore.Authorization;

namespace MyWebApiView.Controllers
{
    public class DataBookController : Controller
    {
        private readonly IDataBookData dataBookData;
        public DataBookController(IDataBookData dBData)
        {
            dataBookData = dBData;
        }

        public void AddTokenToHeader()
        {
            var token = HttpContext.Request.Cookies[".AspNetCore.Application.Id"];
            if (!string.IsNullOrEmpty(token))
                dataBookData.AddTokenToClient(token);
        }

        [HttpGet]
        //[AllowAnonymous]
        public IActionResult Index()
        {
            AddTokenToHeader();

            ViewBag.DataBook = dataBookData.GetAllDatabooks();
            return View();
        }

        [HttpGet]
        //[Authorize]
        public IActionResult GetDataBook(int dataBookId)
        {
            AddTokenToHeader();

            return View(dataBookData.ReadDataBook(dataBookId));
        }

        [HttpGet]
        //[Authorize]
        public IActionResult AddDataBook()
        {
            AddTokenToHeader();

            return View();
        }

        [HttpPost]
        //[Authorize]
        public IActionResult AddDataFromField(DataBook dataBook)
        {
            AddTokenToHeader();

            dataBookData.CreateDataBook(dataBook);
            return Redirect("~/");
        }

        [HttpPost]
        //[Authorize(Roles = "Admin")]
        public IActionResult EditDataBook(int dataBookId)
        {
            AddTokenToHeader();

            return View(dataBookData.ReadDataBook(dataBookId));
        }

        [HttpPost]
        //[Authorize(Roles = "Admin")]
        public IActionResult EditDataFromField(DataBook dataBook)
        {
            AddTokenToHeader();

            dataBookData.UpdateDataBook(dataBook);
            return Redirect("~/");
        }

        [HttpPost]
        //[Authorize(Roles = "Admin")]
        public IActionResult DeleteDataBook(int dataBookId)
        {
            AddTokenToHeader();

            return View(dataBookData.ReadDataBook(dataBookId));
        }

        [HttpPost]
        //[Authorize(Roles = "Admin")]
        public IActionResult DeleteDataFromField(DataBook dataBook)
        {
            AddTokenToHeader();

            dataBookData.DeleteDataBook(dataBook);
            return Redirect("~/");
        }
    }
}

MyWebApi/ViewComponent/LogoutViewViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace MyWebApiView.Component
{
    public class LogoutViewViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }

}

MyWebApi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <style>
        html, body {
            height: 100%;
        }
        body {
            display: flex;
            flex-direction: column;
        }
        .content {
            flex-grow: 1;
        }
    </style>
    <title>@ViewData["Title"] - MyWebApiView</title>
</head>
<body class="container">
    <nav class="navbar navbar-light bg-light" align="center">
        <div> @await Component.InvokeAsync("LogoutView") </div>
    </nav>
    <div class="header" align="center">
        <h1>Записная книжка</h1>
    </div>
    <div class="content">
        @RenderBody()
    </div>

    <style>
        .container {
            padding-top: 10px;
        }

        .validation-summary-errors {
            color: #f00;
        }
    </style>

    <div align="center" class="footer">
        <p>&copy; 2023 - MyWebApiView - <a asp-area="" asp-controller="DataBook" asp-action="Index">Andrew</a></p><br>
    </div>
</body>
</html>